### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by tonyneel923** [WEACOMRU/react-giphy-select#4]
First off great plugin, it is very simple to use and works well. I am having one issue though. When in production this plugin will not work for me as my site uses https and this plugin uses http to call the giphy api. 

I saw the fetch is in the index line 83. Is it possible to add support for both https and http? Possibly via a prop. 

Thanks for your time.

**Comment by bashkos** [comment]
Thanks for this request. I'll try to resolve it in the near future.

**Comment by bashkos** [comment]
Please check release 1.0.3
